apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: nodejs-fouiiral
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/nodejs-fouiiral:6dac25b0802d50add528b3a6db14c95a932df396@sha256:1a83c626bf5a8f7dd0b56a88cc2a65483c0babc6ef7c6a696b2975b8be523da1
        name: container-image  
